language: node_js

node_js:
  - "4"
  - "5"
  - "6"

services:
  - mysql
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c "create database PersTest;" -U postgres
  - mysql -e "create database PersTest;"

script:
  - npm test

after_script:
  - npm run-script coveralls
