CREATE TABLE Customer (
    id INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE "Order" (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	customerId INTEGER,
	dateTime TEXT NOT NULL,
	FOREIGN KEY(customerId) REFERENCES Customer(id)
);

CREATE TABLE "OrderItem" (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	orderId INTEGER,
	productId INTEGER,
	FOREIGN KEY(orderId) REFERENCES "Order"(id),
  FOREIGN KEY(productId) REFERENCES Product(id)
);

CREATE TABLE Product (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	title_tr TEXT NOT NULL,
	title_en TEXT NOT NULL,
	__type TEXT NOT NULL
);
